# constants.py
from enum import Enum, auto

class SweepDirection(Enum):
    FORWARD  = auto()
    BACKWARD = auto()
    
N_COARSE_DRIVING_FREQUENCIES = 2
N_COARSE_DRIVING_AMPLITUDES = 2
N_COARSE_INITIAL_DISPLACEMENTS= 2
N_COARSE_INITIAL_VELOCITIES = 2

MAXIMUM_ORDER_SUBHARMONICS = 10
MAXIMUM_ORDER_SUPERHARMONICS = 10

N_PERIODS_TO_RETAIN = 5

