# constants.py
from enum import Enum, auto

class SweepDirection(Enum):
    FORWARD  = auto()
    BACKWARD = auto()
    
N_COARSE_DRIVING_FREQUENCIES = 50
N_COARSE_DRIVING_AMPLITUDES = 5
N_COARSE_INITIAL_DISPLACEMENTS= 10
N_COARSE_INITIAL_VELOCITIES = 10

MAXIMUM_ORDER_SUBHARMONICS = 10
MAXIMUM_ORDER_SUPERHARMONICS = 10

N_PERIODS_TO_RETAIN = 5

